"""
Sandboxed Code Executor
=======================
Safely executes Python/Pandas code generated by the LLM.
Runs in a restricted environment to prevent malicious code execution.
"""

import io
import sys
import traceback
from contextlib import redirect_stdout, redirect_stderr
from typing import Any, Dict, Optional, Tuple

import pandas as pd

from app.config import get_logger

logger = get_logger(__name__)

# Allowed builtins — restrict dangerous functions
SAFE_BUILTINS = {
    "abs": abs, "all": all, "any": any, "bool": bool, "dict": dict,
    "enumerate": enumerate, "filter": filter, "float": float, "format": format,
    "frozenset": frozenset, "getattr": getattr, "hasattr": hasattr,
    "int": int, "isinstance": isinstance, "len": len, "list": list,
    "map": map, "max": max, "min": min, "print": print, "range": range,
    "reversed": reversed, "round": round, "set": set, "slice": slice,
    "sorted": sorted, "str": str, "sum": sum, "tuple": tuple, "type": type,
    "zip": zip, "True": True, "False": False, "None": None,
}

# Blocked patterns that should never be in generated code
BLOCKED_PATTERNS = [
    "import os", "import sys", "import subprocess",
    "__import__", "eval(", "exec(",
    "open(", "file(",
    "shutil", "pathlib",
    "requests", "urllib",
    "socket", "http",
    "pickle", "shelve",
    "os.system", "os.popen",
    "subprocess.run", "subprocess.call",
]


def extract_code_blocks(response: str) -> list[str]:
    """Extract Python code blocks from Gemini's markdown response."""
    code_blocks = []
    lines = response.split("\n")
    in_code_block = False
    current_block = []

    for line in lines:
        if line.strip().startswith("```python"):
            in_code_block = True
            current_block = []
        elif line.strip() == "```" and in_code_block:
            in_code_block = False
            if current_block:
                code_blocks.append("\n".join(current_block))
        elif in_code_block:
            current_block.append(line)

    return code_blocks


def validate_code(code: str) -> Tuple[bool, Optional[str]]:
    """
    Check code for dangerous patterns before execution.
    Returns (is_safe, error_message).
    """
    for pattern in BLOCKED_PATTERNS:
        if pattern in code:
            return False, f"Blocked pattern detected: '{pattern}'"

    return True, None


def execute_code_safely(
    code: str,
    df: pd.DataFrame,
    timeout_seconds: int = 30,
) -> Dict[str, Any]:
    """
    Execute LLM-generated code in a sandboxed environment.

    The code gets access to:
    - `df`: The pandas DataFrame
    - `pd`: pandas module
    - Standard math/string builtins

    The code does NOT get access to:
    - File system operations
    - Network calls
    - System commands
    - Module imports (except pd, numpy)
    """
    # Validate first
    is_safe, error = validate_code(code)
    if not is_safe:
        logger.warning("code_blocked", reason=error)
        return {
            "success": False,
            "error": f"Code blocked for security: {error}",
            "output": None,
        }

    # Prepare the sandbox
    import numpy as np

    sandbox_globals = {
        "__builtins__": SAFE_BUILTINS,
        "df": df.copy(),  # Copy to prevent mutation
        "pd": pd,
        "np": np,
    }

    # Capture stdout
    stdout_capture = io.StringIO()
    stderr_capture = io.StringIO()

    try:
        with redirect_stdout(stdout_capture), redirect_stderr(stderr_capture):
            exec(code, sandbox_globals)

        stdout_output = stdout_capture.getvalue()

        # Try to find the result variable
        result = None
        for var_name in ["result", "output", "answer", "summary"]:
            if var_name in sandbox_globals:
                result = sandbox_globals[var_name]
                break

        # If no named result, check if last expression created a DataFrame
        if result is None and "result_df" in sandbox_globals:
            result = sandbox_globals["result_df"]

        # Format the result
        formatted_result = _format_result(result, stdout_output)

        logger.info("code_executed_successfully")
        return {
            "success": True,
            "output": formatted_result,
            "stdout": stdout_output,
            "error": None,
        }

    except Exception as e:
        error_msg = f"{type(e).__name__}: {str(e)}"
        logger.error("code_execution_error", error=error_msg)
        return {
            "success": False,
            "output": None,
            "error": error_msg,
            "traceback": traceback.format_exc(),
        }


def _format_result(result: Any, stdout: str) -> str:
    """Format execution result for the response."""
    parts = []

    if stdout and stdout.strip():
        parts.append(stdout.strip())

    if result is not None:
        if isinstance(result, pd.DataFrame):
            parts.append(result.to_string(max_rows=20))
        elif isinstance(result, pd.Series):
            parts.append(result.to_string())
        elif isinstance(result, dict):
            for k, v in result.items():
                parts.append(f"{k}: {v}")
        else:
            parts.append(str(result))

    return "\n".join(parts) if parts else "(Code executed successfully, no output)"
